### ISSUE TITLE
API Limit Hit

### ISSUE THREAD

**Issue by mermelmadness** [vasqued2/ha-teamtracker#77] opened 2023-03-09 15:16 UTC
Woke up this morning to see the following message in Attributes:

```api_message: >-
  Cached data: API_LIMIT hit.  No competition found for 'MIA' between
  2023-03-08T00:00Z and 2023-03-14T00:00Z
```

I don't remember reading anywhere in the Wiki about an API limit.  MIA definitely has games coming up, tomorrow in fact.

**Comment by NRutt2005** [comment] 2023-03-09 21:08
That isn't good. So it be that it is trying to grab the game data from the API too much. Maybe there is a way to limit the amount of times it grabs data when there isn't a live game? Not sure if that is even possible.

**Comment by mermelmadness** [comment] 2023-03-09 21:13
Maybe this has to do with ESPN removing their Dev Center page.  Maybe they're reworking their APIs to be a premium subscription service.

To be fair, I do have 7 instances of Team Tracker integrated into my HA (and had an 8th for a couple of days for testing), but I get data for the rest of them just fine, and am continuing to get live data.

![image](https://user-images.githubusercontent.com/38080873/224160143-d4df7bff-a26a-4729-bb5d-b199d828ab71.png)

Please see what could be the issue.  If it involves reducing the amount of calls made (I know PirateWeather limits free users to 25,000 per month) that would suck.

**Comment by vasqued2** [comment] 2023-03-10 01:34
The API limits the number of games returned to 25 by default.  It returns games from yesterday and then the next 6 days until it hits the 25 game limit.  There have been several times during the pre-season that there have been over 25 games in a 2 day period and the late games on the second day (today) gets dropped.  I suspect that's what's happening here.

Once the season starts, if it keeps happening, I will have to have it start w/ today's games instead of yesterdays.  This will mean post-game results will drop off faster but upcoming games will be returned.

Haven't seen other sports hit the 25 limit.  Just baseball.

**Comment by mermelmadness** [comment] 2023-03-10 01:38
MLB is unique in that each team typically has 5-6 games (sometimes 7) in that 7-day window, and if I have 5 MLB teams I'm following, that's 35.  What would it take to up the amount of games returned beyond 25?

It may be unique per sport because I also have NCAAB (both Top 25 and id: 50) integrated as well.

**Comment by mermelmadness** [comment] 2023-03-10 01:42
Based on what you said, though, it looks like that if I do run into the limit, it'll reset the next day.

**Comment by vasqued2** [comment] 2023-03-10 02:10
The API returns all games in the league for the requested date range until it hits 25 games returned.  The sensor then searches those 25 games to find your team.  You can't specify you only want games for MIA.  It returns them all.  Since MIA isn't one of the first 25 teams it doesn't get data returned for it.  It gives that error message so you know MIA wasn't in the first 25 returned.

**Comment by mermelmadness** [comment] 2023-03-10 02:32
That's insane, though.  4 days a week there are 15 games per day.  The other 3 days there are at least 7.  That means in a given 7-day span there is, at minimum, 81 games to be returned.

**Comment by vasqued2** [comment] 2023-03-10 02:41
While games are going on, the API gets called every 5 seconds.  That's a ton of games and info being returned every minute.  To limit the amount of data returned, they cap it to 25 games.  It's a free, undocumented API.  ESPN can put whatever limits they want on it to control usage and we have to be grateful that it exists and use it accordingly.

The alternative is what people describe about.  ESPN will throttle the number of calls or move it to a premium service.

And you don't need all 50-60 NHL games returned at once.  The sensor only displays 1 game per team so if you go back one day and then look forward, it will find the game on or before gameday.  Only baseball w/ tons of back-to-backs and double headers hits the limit.

**Comment by mermelmadness** [comment] 2023-03-10 03:28
@NRutt2005 Yes, NCAA Basketball

**Comment by mermelmadness** [comment] 2023-03-10 03:29
@vasqued2 I see.  Hmm.  So, did I just get unlucky that one of the teams I follow was beyond the first 25 games for the day, or is it because I have 7 integrations, 2 of which span the entire league?

**Comment by vasqued2** [comment] 2023-03-10 03:36
You were just unlucky.  It seems to generally sort them based on start time so late/west coast games get cut off most often but not always.

If you have multiple sensors from the same league it will cache the API data and use it both both teams instead of recalling the API again so that saves some API calls.

**Comment by NRutt2005** [comment] 2023-03-10 03:45
@vasqued2 any chance of getting College Baseball and College Softball added to the integration? I found the baseball and softball api url but I can't seem to get the data to come in.

Thanks!

**Comment by mermelmadness** [comment] 2023-03-10 03:45
I assume that's only if the teams I integrated are playing each other.  Damn.  I integrated all 5 teams from the NL East so I could create live standings next to my live scoreboard.

![image](https://user-images.githubusercontent.com/38080873/224218038-40ec53f8-7b2f-4071-bf81-ea84c6932b71.png)

With MIA at null, it ruins the whole formula.

```
nl_east:
        friendly_name: "NL East"
        value_template: >-
          {% set teams = [
            {'name': 'NYM', 'record': state_attr('sensor.mets','team_record'), 'percentage': '{:.3f}'.format(float(states('sensor.mets_win_percentage'))) | replace('0.','.') },
            {'name': 'PHI', 'record': state_attr('sensor.phillies','team_record'), 'percentage': '{:.3f}'.format(float(states('sensor.phillies_win_percentage'))) | replace('0.','.') },
            {'name': 'MIA', 'record': state_attr('sensor.marlins','team_record'), 'percentage': '{:.3f}'.format(float(states('sensor.marlins_win_percentage'))) | replace('0.','.') },
            {'name': 'ATL', 'record': state_attr('sensor.braves','team_record'), 'percentage': '{:.3f}'.format(float(states('sensor.braves_win_percentage'))) | replace('0.','.') },
            {'name': 'WSH', 'record': state_attr('sensor.nationals','team_record'), 'percentage': '{:.3f}'.format(float(states('sensor.nationals_win_percentage'))) | replace('0.','.') },
          ] %}
          {% set sorted_teams = teams | sort(attribute='percentage', reverse=true) %}
          {% set formatted_teams = sorted_teams | map(attribute='name') | join(', ') %}
          {% set formatted_percentages = sorted_teams | map(attribute='percentage') | join(', ') %}
          {% set formatted_records = sorted_teams | map(attribute='record') | join(', ') %}
          Teams: {{ formatted_teams }} 
          Team Records: {{ formatted_records }}
          Winning Percentages: {{ formatted_percentages }}
```

Any suggestions on how I could possibly avoid this going forward, if at all?  Does ESPN have a paid sub that will give you more than 25 games?

**Comment by NRutt2005** [comment] 2023-03-10 04:28
I don't think they have a premium API subscription. If they did, I bet it wouldn't be cheap. It's ESPN after all. The API is not even published anywhere that I've been able to find. I wish they would at least have a API info site that provides some kind of break down of limitations and all.

**Comment by mermelmadness** [comment] 2023-03-10 05:03
With midnight came a refresh and MIA came back.  Guess it'll just be like this throughout the season....or maybe just Spring Training.  Who knows?

@vasqued2 If you have any ideas on how to avoid this for MLB I'd be open to any suggestions.  Let me know if I can help in any way if you plan to address this.  If you don't, thanks for making this integration.  I love it.

**Comment by vasqued2** [comment] 2023-03-25 23:25
You can try the pre-release version in `master` to see if it resolves it or wait a couple days for the official release.

**Comment by mermelmadness** [comment] 2023-03-25 23:29
I'll wait.  Not in a rush.  Thanks for looking into this.  Will report after update becomes available in HACS.

**Comment by vasqued2** [comment] 2023-03-25 23:55
Sounds good.  Trying to release before opening day because I know it'll hit the limit then, but having some issues w/ HACS right now.

Basically, it will only return games for a single day and rely on the ESPN API to determine when to switch to the current day games.  Near as I can tell, it returns yesterday's games until about noon EST and then cuts over to the current day.  Downside it if there is not game for the day the API returns data for, it will return a status of NOT_FOUND.

**Comment by mermelmadness** [comment] 2023-03-26 00:06
For baseball I think that's fine.  Other sports that don't play every day I can see that being annoying, but 95% of the time the status will either be `PRE` or `POST`

I know I'm one person, but I'm fine with this.

**Comment by mermelmadness** [comment] 2023-03-26 00:10
Also, I don't know enough to download the `master` code and install it manually.  I'm sure I could figure it out, but I'm tired.

**Comment by vasqued2** [comment] 2023-03-26 13:19
You should be able to upgrade to v0.7.2 and see how it goes.  Games should cutover from yesterday to today around noon EST.  I haven't paid attention to the exact time.

**Comment by mermelmadness** [comment] 2023-03-26 13:30
Updated to 0.7.2 and it's showing today's game as `PRE`.  This is the last preseason game and opening day is Thursday, so there'll be a good sized gap between games.  I'll report on what I see.

**Comment by vasqued2** [comment] 2023-03-26 13:34
Thanks.  I'll leave this open and you can let me know if there are any issues.

**Comment by mermelmadness** [comment] 2023-03-26 15:25
I can report that all 5 MLB teams I have integrated (the whole NL East) are all showing `PRE` as their state.

**Comment by vasqued2** [comment] 2023-04-01 11:15
Made it through opening day with all teams playing and API call is working as intended, pulling back a single day's games (i.e. either yesterday or today depending on the cutover time).

Closing as resolved, although opening another baseball related defect related to the NOT_FOUND date.

**Closed by vasqued2** 2023-04-01 11:15 UTC
