### ISSUE TITLE
Research ?

### ISSUE THREAD

**Issue by schumi2309** [vasqued2/ha-teamtracker#45] opened 2022-12-19 04:28 UTC
Hello,
How to do a search to know what to wear for such and such a team, or for such a tennis player?
To search for example Barcelona or Rafael Nadal?
where to find the right name to put in the integration?

Thank you

**Comment by vasqued2** [comment] 2022-12-20 00:17
From the readme…

—-
For the Team, you'll need to know the team ID ESPN uses for your team. This is the 2-, 3- or 4-letter abbreviation (eg. "SEA" for Seattle or "NE" for New England) ESPN uses when space is limited. You can generally find them at https://espn.com/ in the top scores UI, but they can also be found in other pages with team stats as well.

For individual sports, you should specify the althlete's name in team_id field. This will cause the sensor to track the competitions matching the name of the specified athlete. You should use as much of the name (i.e. last name, full name) as needed to uniquely identify the athlete.
—-

Are there some you are having trouble with?  I believe BAR and Nadal should work.

**Comment by schumi2309** [comment] 2022-12-20 11:27
Thanks for this info.
Concerning barcelona and nadal, in the field, I put this:
NADAL
BAR
and the result gives me:

NOT_FOUND

So I tried with several abbreviations but it didn't work. I continue my research.
Thank you.

**Comment by vasqued2** [comment] 2022-12-20 18:44
That's because there are no LIGA or WTA games scheduled in the next 5 days or so.  The `api_message` on sensor should have a message to that effect.

https://github.com/vasqued2/ha-teamtracker/wiki/Troubleshooting:--State-=--NOT_FOUND

**Comment by schumi2309** [comment] 2022-12-21 07:39
All right.

I understand and it's good.

Thanks...

**Comment by vasqued2** [comment] 2022-12-26 11:40
The Barcelona/Espanyol game should be showing up now.  If not, you have something set up wrong.  Please confirm and close if it is working.  If it isn’t working, please post your yaml or what your sensor values are.

**Comment by vasqued2** [comment] 2022-12-31 14:21
Confirmed Barca is working if the sensor is set up correctly.  Closing.

**Closed by vasqued2** 2022-12-31 14:21 UTC
