### ISSUE TITLE
Hyperlinks show up as large text over images, only in iOS app

### ISSUE THREAD

**Issue by boctok** [vasqued2/ha-teamtracker#173] opened 2024-08-17 01:51 UTC
No idea why it only happens in the official HA iOS and I can’t really say why it is happening. Nothing shows up in the logs.

Here’s an image:

![IMG_0518](https://github.com/user-attachments/assets/5eaf704b-2b01-4d8c-b2a7-7e202851da2f)

**Comment by imist** [comment] 2024-08-17 07:37
This is same as [https://github.com/vasqued2/ha-teamtracker-card/issues/95](https://github.com/vasqued2/ha-teamtracker-card/issues/95)

**Comment by vasqued2** [comment] 2024-08-17 11:59
This was introduced in HA 2024.8.0 when they suddenly began classifying several additional devices as legacy and there is a limitation in the code that handles legacy devices the causes the card to render incorrectly.  There was also a defect that caused iPads to be treated as legacy.  Combined, this causes the problem.

The HA team is fixing the iPad defect so it will be classified correctly and this should correct the problem for iPads.  I will be making some changes to the card so that will take the limitation into account so it will work for other legacy devices.  Hopefully I will have this out this weekend.

In the meantime, the link above has an empty card workaround you can use to get the card to display correctly.

**Comment by vasqued2** [comment] 2024-08-18 22:42
I have released v0.14.2-beta1 to address this issue.

Please see discussion thread https://github.com/vasqued2/ha-teamtracker-card/discussions/97 for details and log any issues in that discussion thread or the open issue in the card repo.

**Comment by boctok** [comment] 2024-08-19 00:57
Thanks!

**Comment by vasqued2** [comment] 2024-08-24 14:35
This should be fixed in v0.14.2

**Closed by vasqued2** 2024-08-24 14:35 UTC
